workflows:
  android-release:
    name: Android Release
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      android_signing:
        - tradex-upload-key.jks

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release \
            --dart-define=TRADEX_BASE_URL="$TRADEX_BASE_URL"

    artifacts:
      - build/app/outputs/bundle/release/*.aab
