@extends('admin.layout')

@section('title', 'Users')
@section('heading', 'User management')

@section('content')
    <div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
        <div>
            <p class="text-sm leading-6 text-slate-500">Review every registered application account and its ownership.</p>
            <p class="mt-1 text-xs text-slate-400">Deleting an account also removes its owned records and uploaded files.</p>
        </div>
        <div class="rounded-xl bg-indigo-50 px-4 py-2 text-sm font-semibold text-indigo-700">{{ $users->total() }} users</div>
    </div>
    @if (session('status'))<div class="mb-6 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">{{ session('status') }}</div>@endif
    @if ($errors->any())<div class="mb-6 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{{ $errors->first('user') }}</div>@endif
    <section class="mb-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm shadow-slate-200/40">
        <form method="GET" action="{{ route('admin.users.index') }}" class="grid gap-4 md:grid-cols-[1fr_180px_180px_auto] md:items-end">
            <div><label for="search" class="mb-2 block text-xs font-semibold uppercase tracking-wider text-slate-500">Search users</label><input id="search" name="search" value="{{ request('search') }}" type="search" placeholder="Name, email, or phone" class="block w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm outline-none focus:border-indigo-400 focus:bg-white focus:ring-4 focus:ring-indigo-500/10"></div>
            <div><label for="role" class="mb-2 block text-xs font-semibold uppercase tracking-wider text-slate-500">Account type</label><select id="role" name="role" class="block w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm outline-none focus:border-indigo-400 focus:bg-white focus:ring-4 focus:ring-indigo-500/10"><option value="">All types</option><option value="client" @selected(request('role') === 'client')>Client</option><option value="merchant" @selected(request('role') === 'merchant')>Merchant</option></select></div>
            <div><label for="status" class="mb-2 block text-xs font-semibold uppercase tracking-wider text-slate-500">Status</label><select id="status" name="status" class="block w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm outline-none focus:border-indigo-400 focus:bg-white focus:ring-4 focus:ring-indigo-500/10"><option value="">All statuses</option>@foreach (['active', 'inactive', 'banned'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ ucfirst($status) }}</option>@endforeach</select></div>
            <button type="submit" class="rounded-xl bg-slate-900 px-5 py-3 text-sm font-semibold text-white transition hover:bg-slate-700">Apply filters</button>
        </form>
    </section>
    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm shadow-slate-200/40"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-100 text-left"><thead class="bg-slate-50"><tr class="text-[11px] font-semibold uppercase tracking-wider text-slate-500"><th class="px-6 py-3">User</th><th class="px-6 py-3">Type</th><th class="px-6 py-3">Store</th><th class="px-6 py-3">Status</th><th class="px-6 py-3">Registered</th><th class="px-6 py-3 text-right">Action</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($users as $user)<tr class="align-top text-sm transition hover:bg-slate-50/80"><td class="px-6 py-5"><p class="font-semibold text-slate-900">{{ $user->name }}</p><p class="mt-1 text-xs text-slate-500">{{ $user->email }}</p></td><td class="px-6 py-5"><span class="inline-flex rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold capitalize text-slate-600">{{ $user->role }}</span></td><td class="px-6 py-5 text-slate-600">@if ($user->isMerchant()){{ $user->stores->first()?->store_name ?? 'No store' }}@else — @endif</td><td class="px-6 py-5"><span class="inline-flex rounded-full px-2.5 py-1 text-xs font-semibold capitalize {{ $user->status === 'active' ? 'bg-emerald-50 text-emerald-700' : ($user->status === 'banned' ? 'bg-rose-50 text-rose-700' : 'bg-amber-50 text-amber-700') }}">{{ $user->status }}</span></td><td class="whitespace-nowrap px-6 py-5 text-xs text-slate-500">{{ $user->created_at?->format('M j, Y') ?? '—' }}</td><td class="px-6 py-5 text-right">@if ($user->isClient() || $user->isMerchant())<form method="POST" action="{{ route('admin.users.destroy', $user) }}" onsubmit="return confirm('Delete this user and all of their owned data and files? This cannot be undone.')">@csrf @method('DELETE')<button type="submit" class="font-semibold text-rose-600 hover:text-rose-800">Delete</button></form>@else<span class="text-xs text-slate-400">Protected</span>@endif</td></tr>@empty<tr><td colspan="6" class="px-6 py-14 text-center text-sm text-slate-400">No users match the current filters.</td></tr>@endforelse</tbody></table></div>@if ($users->hasPages())<div class="border-t border-slate-100 px-6 py-4">{{ $users->links() }}</div>@endif</section>
@endsection
