@extends('admin.layout')

@section('title', 'Stores')
@section('heading', 'Store management')

@section('content')
    <div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm leading-6 text-slate-500">Review store ownership, inventory, orders, and operational status.</p><p class="mt-1 text-xs text-slate-400">Status changes use the existing admin store service and validation.</p></div><div class="rounded-xl bg-indigo-50 px-4 py-2 text-sm font-semibold text-indigo-700">{{ $stores->total() }} stores</div></div>
    @if (session('status'))<div class="mb-6 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">{{ session('status') }}</div>@endif
    <section class="mb-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm shadow-slate-200/40"><form method="GET" action="{{ route('admin.stores.index') }}" class="grid gap-4 md:grid-cols-[1fr_200px_auto] md:items-end"><div><label for="search" class="mb-2 block text-xs font-semibold uppercase tracking-wider text-slate-500">Search stores or merchants</label><input id="search" name="search" value="{{ request('search') }}" type="search" placeholder="Store, name, email, or phone" class="block w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm focus:border-indigo-400 focus:bg-white focus:ring-4 focus:ring-indigo-500/10"></div><div><label for="status" class="mb-2 block text-xs font-semibold uppercase tracking-wider text-slate-500">Status</label><select id="status" name="status" class="block w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm focus:border-indigo-400 focus:bg-white focus:ring-4 focus:ring-indigo-500/10"><option value="">All statuses</option>@foreach ($statuses as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ ucfirst($status) }}</option>@endforeach</select></div><button type="submit" class="rounded-xl bg-slate-900 px-5 py-3 text-sm font-semibold text-white transition hover:bg-slate-700">Apply filters</button></form></section>
    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm shadow-slate-200/40"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-100 text-left"><thead class="bg-slate-50"><tr class="text-[11px] font-semibold uppercase tracking-wider text-slate-500"><th class="px-6 py-3">Store</th><th class="px-6 py-3">Merchant</th><th class="px-6 py-3">Products</th><th class="px-6 py-3">Orders</th><th class="px-6 py-3">Status</th><th class="px-6 py-3"></th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($stores as $store)<tr class="text-sm"><td class="px-6 py-4"><a href="{{ route('admin.stores.show', $store) }}" class="font-semibold text-indigo-700 hover:text-indigo-900">{{ $store->store_name }}</a><p class="text-xs text-slate-400">#{{ $store->id }}</p></td><td class="px-6 py-4"><p class="font-medium text-slate-700">{{ $store->owner?->name ?? '—' }}</p><p class="text-xs text-slate-400">{{ $store->owner?->email ?? '—' }}</p></td><td class="px-6 py-4 text-slate-600">{{ $store->products_count }}</td><td class="px-6 py-4 text-slate-600">{{ $store->orders_count }}</td><td class="px-6 py-4"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold capitalize text-slate-600">{{ $store->status }}</span></td><td class="px-6 py-4 text-right"><a href="{{ route('admin.stores.show', $store) }}" class="font-semibold text-indigo-700 hover:text-indigo-900">View</a></td></tr>@empty<tr><td colspan="6" class="px-6 py-12 text-center text-sm text-slate-400">No stores match the selected filters.</td></tr>@endforelse</tbody></table></div>@if ($stores->hasPages())<div class="border-t border-slate-100 px-6 py-4">{{ $stores->links() }}</div>@endif</section>
@endsection