@extends('admin.layout')

@section('title', 'Store · '.$store->store_name)
@section('heading', 'Store details')

@section('content')
    <div class="mb-6"><a href="{{ route('admin.stores.index') }}" class="text-sm font-semibold text-indigo-700 hover:text-indigo-900">← Back to stores</a></div>
    @if (session('status'))<div class="mb-6 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">{{ session('status') }}</div>@endif
    @if ($errors->any())<div class="mb-6 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800"><ul class="list-disc space-y-1 pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="grid gap-6 xl:grid-cols-[1fr_1.4fr]"><section class="h-fit rounded-2xl border border-slate-200 bg-white p-6 shadow-sm shadow-slate-200/40"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-semibold uppercase tracking-wider text-slate-400">Store #{{ $store->id }}</p><h2 class="mt-1 text-xl font-semibold text-slate-900">{{ $store->store_name }}</h2></div><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold capitalize text-slate-600">{{ $store->status }}</span></div><dl class="mt-6 space-y-4 text-sm"><div><dt class="text-xs font-semibold uppercase tracking-wider text-slate-400">Merchant</dt><dd class="mt-1 font-medium text-slate-800">{{ $store->owner?->name ?? '—' }}</dd><dd class="text-slate-500">{{ $store->owner?->email ?? '—' }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wider text-slate-400">Description</dt><dd class="mt-1 leading-6 text-slate-600">{{ $store->description ?: 'No description provided.' }}</dd></div></dl><form method="POST" action="{{ route('admin.stores.status', $store) }}" class="mt-6 border-t border-slate-100 pt-5">@csrf @method('PUT')<label for="status" class="mb-2 block text-xs font-semibold uppercase tracking-wider text-slate-500">Update status</label><div class="flex gap-3"><select id="status" name="status" class="min-w-0 flex-1 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm focus:border-indigo-400 focus:bg-white focus:ring-4 focus:ring-indigo-500/10">@foreach (['active', 'inactive', 'suspended'] as $status)<option value="{{ $status }}" @selected($store->status === $status)>{{ ucfirst($status) }}</option>@endforeach</select><button type="submit" class="rounded-xl bg-slate-900 px-4 py-3 text-sm font-semibold text-white hover:bg-slate-700">Save</button></div></form></section><section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm shadow-slate-200/40"><div class="border-b border-slate-100 px-6 py-5"><h2 class="font-semibold text-slate-900">Product summary</h2><p class="mt-1 text-xs text-slate-400">{{ $store->products_count }} total products · {{ $store->orders_count }} total orders</p></div><div class="divide-y divide-slate-100">@forelse ($store->products as $product)<div class="flex items-center justify-between gap-4 px-6 py-4 text-sm"><div><a href="{{ route('admin.products.show', $product) }}" class="font-medium text-indigo-700 hover:text-indigo-900">{{ $product->name }}</a><p class="text-xs capitalize text-slate-400">{{ $product->status }}</p></div><span class="text-slate-600">{{ number_format((float) $product->price, 2) }}</span></div>@empty<p class="px-6 py-10 text-sm text-slate-400">No products recorded for this store.</p>@endforelse</div></section></div>
@endsection