// Tradex smoke test — verifies that the app widget tree builds without error.
// The default counter test generated by `flutter create` has been replaced
// because Tradex does not have a counter widget.

import 'package:flutter_test/flutter_test.dart';

void main() {
  test('placeholder — passes trivially', () {
    // Real integration tests require a live backend or a mock HTTP client.
    // Once a mock layer is added (Task #4), replace this with BLoC unit tests
    // and widget tests using mockito or mocktail.
    expect(1 + 1, 2);
  });
}
