@extends('admin.layout')

@section('title', 'Products')
@section('heading', 'Product monitoring')

@section('content')
    <div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm leading-6 text-slate-500">Monitor products across all merchant stores.</p><p class="mt-1 text-xs text-slate-400">This admin surface is read-only because the existing admin product contract is read-only.</p></div><div class="rounded-xl bg-indigo-50 px-4 py-2 text-sm font-semibold text-indigo-700">{{ $products->total() }} products</div></div>
    @if (session('status'))<div class="mb-6 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">{{ session('status') }}</div>@endif
    <section class="mb-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm shadow-slate-200/40">
        <form method="GET" action="{{ route('admin.products.index') }}" class="grid gap-4 md:grid-cols-[1.4fr_1fr_1fr_150px_auto] md:items-end">
            <div><label for="search" class="mb-2 block text-xs font-semibold uppercase tracking-wider text-slate-500">Search</label><input id="search" name="search" value="{{ request('search') }}" type="search" placeholder="Product name or description" class="block w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm focus:border-indigo-400 focus:bg-white focus:ring-4 focus:ring-indigo-500/10"></div>
            <div><label for="category_id" class="mb-2 block text-xs font-semibold uppercase tracking-wider text-slate-500">Category</label><select id="category_id" name="category_id" class="block w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm focus:border-indigo-400 focus:bg-white focus:ring-4 focus:ring-indigo-500/10"><option value="">All categories</option>@foreach ($categories as $category)<option value="{{ $category->id }}" @selected((string) request('category_id') === (string) $category->id)>{{ $category->name }}</option>@endforeach</select></div>
            <div><label for="status" class="mb-2 block text-xs font-semibold uppercase tracking-wider text-slate-500">Status</label><select id="status" name="status" class="block w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm focus:border-indigo-400 focus:bg-white focus:ring-4 focus:ring-indigo-500/10"><option value="">All statuses</option>@foreach ($statuses as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ ucfirst(str_replace('_', ' ', $status)) }}</option>@endforeach</select></div>
            <div><label for="sort_by" class="mb-2 block text-xs font-semibold uppercase tracking-wider text-slate-500">Sort by</label><select id="sort_by" name="sort_by" class="block w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm focus:border-indigo-400 focus:bg-white focus:ring-4 focus:ring-indigo-500/10">@foreach (['created_at' => 'Newest', 'name' => 'Name', 'price' => 'Price', 'quantity' => 'Stock'] as $value => $label)<option value="{{ $value }}" @selected(request('sort_by', 'created_at') === $value)>{{ $label }}</option>@endforeach</select></div>
            <button type="submit" class="rounded-xl bg-slate-900 px-5 py-3 text-sm font-semibold text-white transition hover:bg-slate-700">Apply</button>
        </form>
    </section>
    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm shadow-slate-200/40"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-100 text-left"><thead class="bg-slate-50"><tr class="text-[11px] font-semibold uppercase tracking-wider text-slate-500"><th class="px-6 py-3">Product</th><th class="px-6 py-3">Merchant / store</th><th class="px-6 py-3">Category</th><th class="px-6 py-3">Price</th><th class="px-6 py-3">Stock</th><th class="px-6 py-3">Status</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($products as $product)<tr class="text-sm"><td class="px-6 py-4"><a href="{{ route('admin.products.show', $product) }}" class="font-semibold text-indigo-700 hover:text-indigo-900">{{ $product->name }}</a><p class="text-xs text-slate-400">#{{ $product->id }}</p></td><td class="px-6 py-4 text-slate-600">{{ $product->store?->store_name ?? 'Store unavailable' }}</td><td class="px-6 py-4 text-slate-500">{{ $product->category?->name ?? 'Uncategorized' }}</td><td class="px-6 py-4 font-semibold text-slate-700">{{ number_format((float) $product->price, 2) }}</td><td class="px-6 py-4 text-slate-600">{{ $product->quantity }}</td><td class="px-6 py-4"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold capitalize text-slate-600">{{ str_replace('_', ' ', $product->status) }}</span></td></tr>@empty<tr><td colspan="6" class="px-6 py-12 text-center text-sm text-slate-400">No products match the selected filters.</td></tr>@endforelse</tbody></table></div>@if ($products->hasPages())<div class="border-t border-slate-100 px-6 py-4">{{ $products->links() }}</div>@endif</section>
@endsection