<section class="max-w-2xl rounded-2xl border border-slate-200 bg-white p-6 shadow-sm shadow-slate-200/40">
    @if ($errors->any())<div class="mb-6 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800"><ul class="list-disc space-y-1 pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form method="POST" action="{{ $formAction }}" enctype="multipart/form-data" class="space-y-5">
        @csrf
        @if ($method !== 'POST') @method($method) @endif
        <div><label for="name" class="mb-2 block text-xs font-semibold uppercase tracking-wider text-slate-500">Name</label><input id="name" name="name" value="{{ old('name', $category?->name) }}" required maxlength="100" class="block w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm focus:border-indigo-400 focus:bg-white focus:ring-4 focus:ring-indigo-500/10">@error('name')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
        <div><label for="status" class="mb-2 block text-xs font-semibold uppercase tracking-wider text-slate-500">Status</label><select id="status" name="status" class="block w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm focus:border-indigo-400 focus:bg-white focus:ring-4 focus:ring-indigo-500/10"><option value="active" @selected(old('status', $category?->status ?? 'active') === 'active')>Active</option><option value="inactive" @selected(old('status', $category?->status) === 'inactive')>Inactive</option></select>@error('status')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
        <div><label for="image" class="mb-2 block text-xs font-semibold uppercase tracking-wider text-slate-500">Image <span class="font-normal normal-case tracking-normal text-slate-400">(optional, max 2 MB)</span></label><input id="image" name="image" type="file" accept=".jpg,.jpeg,.png,.webp" class="block w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm">@error('image')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
        <div class="flex justify-end gap-3 pt-2"><a href="{{ route('admin.categories.index') }}" class="rounded-xl px-5 py-3 text-sm font-semibold text-slate-500 hover:bg-slate-100">Cancel</a><button type="submit" class="rounded-xl bg-slate-900 px-5 py-3 text-sm font-semibold text-white transition hover:bg-slate-700">{{ $submitLabel }}</button></div>
    </form>
</section>