@extends('admin.layout')

@section('title', 'Categories')
@section('heading', 'Category management')

@section('content')
    <div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm leading-6 text-slate-500">Manage the marketplace categories used by merchant products.</p><p class="mt-1 text-xs text-slate-400">Delete is guarded by the existing category service when products are still assigned.</p></div><a href="{{ route('admin.categories.create') }}" class="rounded-xl bg-slate-900 px-5 py-3 text-sm font-semibold text-white transition hover:bg-slate-700">New category</a></div>
    @if (session('status'))<div class="mb-6 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">{{ session('status') }}</div>@endif
    @if ($errors->any())<div class="mb-6 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800"><ul class="list-disc space-y-1 pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <section class="mb-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm shadow-slate-200/40"><form method="GET" action="{{ route('admin.categories.index') }}" class="grid gap-4 md:grid-cols-[1fr_200px_auto] md:items-end"><div><label for="search" class="mb-2 block text-xs font-semibold uppercase tracking-wider text-slate-500">Search categories</label><input id="search" name="search" value="{{ request('search') }}" type="search" placeholder="Category name" class="block w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm focus:border-indigo-400 focus:bg-white focus:ring-4 focus:ring-indigo-500/10"></div><div><label for="status" class="mb-2 block text-xs font-semibold uppercase tracking-wider text-slate-500">Status</label><select id="status" name="status" class="block w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm focus:border-indigo-400 focus:bg-white focus:ring-4 focus:ring-indigo-500/10"><option value="">All statuses</option>@foreach ($statuses as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ ucfirst($status) }}</option>@endforeach</select></div><button type="submit" class="rounded-xl bg-slate-900 px-5 py-3 text-sm font-semibold text-white transition hover:bg-slate-700">Apply filters</button></form></section>
    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm shadow-slate-200/40"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-100 text-left"><thead class="bg-slate-50"><tr class="text-[11px] font-semibold uppercase tracking-wider text-slate-500"><th class="px-6 py-3">Category</th><th class="px-6 py-3">Products</th><th class="px-6 py-3">Status</th><th class="px-6 py-3">Created</th><th class="px-6 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($categories as $category)<tr class="text-sm"><td class="px-6 py-4"><p class="font-semibold text-slate-800">{{ $category->name }}</p><p class="text-xs text-slate-400">#{{ $category->id }}</p></td><td class="px-6 py-4 text-slate-600">{{ $category->products_count ?? 0 }}</td><td class="px-6 py-4"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold capitalize text-slate-600">{{ $category->status }}</span></td><td class="px-6 py-4 text-slate-500">{{ $category->created_at?->format('M j, Y') }}</td><td class="px-6 py-4"><div class="flex justify-end gap-3"><a href="{{ route('admin.categories.edit', $category) }}" class="font-semibold text-indigo-700 hover:text-indigo-900">Edit</a><form method="POST" action="{{ route('admin.categories.destroy', $category) }}" onsubmit="return confirm('Delete this category?')">@csrf @method('DELETE')<button type="submit" class="font-semibold text-rose-600 hover:text-rose-800">Delete</button></form></div></td></tr>@empty<tr><td colspan="5" class="px-6 py-12 text-center text-sm text-slate-400">No categories match the selected filters.</td></tr>@endforelse</tbody></table></div>@if ($categories->hasPages())<div class="border-t border-slate-100 px-6 py-4">{{ $categories->links() }}</div>@endif</section>
@endsection